# Generated by Django 3.1.2 on 2020-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='pdf',
            field=models.FileField(default='', upload_to='pdfs'),
            preserve_default=False,
        ),
    ]
