# Generated by Django 3.1.2 on 2020-11-29 10:46

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_physics_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physics',
            name='lecture',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='physics',
            name='pdf',
            field=models.FileField(blank=True, default=None, upload_to='pdfs'),
        ),
    ]
