# Generated by Django 3.1.2 on 2020-11-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Physics',
            new_name='Youtube',
        ),
    ]
